### ISSUE TITLE
Containing Classifier is null in AgreeASTBuilder line 911

### ISSUE THREAD

**Issue by dkstewart** [loonwerks/AGREE#30] opened 2020-07-27 15:30 UTC
The analysis will not complete for certain examples due to a null pointer exception being thrown in AgreeASTBuilder line 911. For certain connections, the containing classifier is null. Attached zip file with two examples showing this problem while using Agree master branch v. 2.5.1. 

Sensor_Example: Reactor_Sys.aadl -> Reactor_Sys.W_Voting -> Verify All Layers or Verify Single Layer
Simple_Sensor: Top_Level.aadl -> Top_Level.impl -> Verify All Layers or Verify Single Layer

[AgreeBug.zip](https://github.com/loonwerks/AGREE/files/4982855/AgreeBug.zip)

**Comment by kfhoech** [comment] 2020-07-27 16:57
Confirmed.

This is a devilish problem.  To support the type extension AGREE needs to traverse the instance model for connections otherwise it gets only the base types (and not the extensions) since the connections are only on the bases.  But, the instance model collapses connections that can be linked across multiple layers into one connection instance.  This occurs in your simple example where the top level connects the temperature to its subcomponent and that subcomponent connects it to its subcomponent.  The AGREE translation needs to unwind these back through the connection references to the original connections, but that loses the type refinements and some of the references may be irrelevant depending on context.

**Comment by dkstewart** [comment] 2020-07-31 16:27
Fan out connections giving a "multiple connections" exception in Agree analysis. Model attached. 
Top level: Reactor_Sys.aadl
Top level impl to run: Reactor_Sys.W_Voting
Verify All Layers

[Sensor_Example.zip](https://github.com/loonwerks/AGREE/files/5007992/Sensor_Example.zip)

**Comment by kfhoech** [comment] 2020-08-03 20:21
Fixed by pull request #36.

**Closed by kfhoech** 2020-08-03 20:21 UTC
Labels: AGREE, bug
