### ISSUE TITLE
AGREE Simulator Error

### ISSUE THREAD

**Issue by cong-liu-2000** [loonwerks/AGREE#61] opened 2021-02-24 18:11 UTC
An  "AGREE Simulator Error" window pops up while simulating Phase 2 model.
The first step is OK. But clicking "Step Forward" triggers the error.
Captured pop-up window, error trace, and Lustre model are attached.

![Capture](https://user-images.githubusercontent.com/70218414/109045120-0cf5d780-7688-11eb-9dec-f807405e0662.JPG)
[trace.txt](https://github.com/loonwerks/AGREE/files/6037929/trace.txt)
[sw_lustre.txt](https://github.com/loonwerks/AGREE/files/6037962/sw_lustre.txt)

**Comment by konrad-slind** [comment] 2021-02-24 21:10
Might have something to do with the array quantifiers used to implement
IS_TRUSTED

**Comment by kfhoech** [comment] 2021-02-25 16:04
Confirmed.

The simulator includes a visitor that inlines all node calls.  However, the went wrong, because of a bug in the AGREE translation process where visiting of expressions for Id substitution would errantly replace a NodeCallExpr with a FunctionCallExpr where the referenced call was a Node rather than a Function.  This would then cause the node inlining visitor to miss inlining and and emission of the inlined node. 

The solution appears to be to replace the custom Id substitution with the standard JKind SubstitutionVisitor.

**Comment by kfhoech** [comment] 2021-02-25 21:24
Fixed by #62.

**Closed** 2021-02-25 21:25 UTC
Labels: AGREE, bug
