### ISSUE TITLE
AGREE java validator not throwing type mismatch error

### ISSUE THREAD

**Issue by bcbrusse** [loonwerks/AGREE#32] opened 2020-07-30 21:08 UTC
For some reason the agree java validator is not picking up on the type mismatches anymore. It was also established that I do not have the developer version that could allow me to disable the AGREE validator. 

package test1
public

	with Base_Types;
	
	annex agree {**
		const TEST: real = 10; -- should throw an error;
	**};
	
	system A
		features
			Input: in data port Base_Types::Float;
			Output: out data port Base_Types::Float;			
		annex agree {**
			assume "" : Input < 20;
		**};
	end A;
	
	system S
		features
			Input: in data port Base_Types::Float;
			Output: out data port Base_Types::Float;
		annex agree {**
			assume "" : Input < TEST; -- should throw an error
		**};
	end S;
	
	system implementation S.impl
		subcomponents
			A: system A;
		connections
			c1_a: port Input -> A.Input; 
			c2_a: port A.Output -> Output;
	end S.impl;

end test1;

**Comment by kfhoech** [comment] 2020-08-04 12:15
Confirmed.

This is due to commit 2c35fff510e86322b82482436c885f36cfae74ac.

**Comment by kfhoech** [comment] 2020-08-04 16:25
Fixed by commit 6a70546bc23833bdb0b51341e39b2b2dfb1bc397.

**Closed by kfhoech** 2020-08-04 16:25 UTC
Labels: AGREE, bug
