### ISSUE TITLE
'forall' Scope Error For AGREE Node

### ISSUE THREAD

**Issue by bcbrusse** [loonwerks/AGREE#53] opened 2021-01-26 20:09 UTC
The variable "a" is not recognized by the node definition with the following error "Only arguments, constants, and node calls allowed within a node". Local variables introduced through checks like "forall" should be supported. 

Bound variable is not being placed in scope as it should be when in a node.

Also, having to add () around the forall expression was tricky to catch.

	package Forall_Array_Node
	public
	
	with Data_Model;
	with Base_Types;
	
	data array_type
		properties
			Data_Model::Data_Representation => Array;
            Data_Model::Base_Type => (classifier (Base_Types::Unsigned_8));
            Data_Model::Dimension => (32);
            Data_Size => 32 Bytes;
	end array_type;
	
	annex agree {**
			
		node ChangedArray(array: array_type, init: bool) returns (o: bool);
		let
			o = init -> (forall a in array, a != pre(a)); -- it was determined that () were necessary here
		tel;
		
	**};
	
	end Forall_Array_Node;

**Comment by kfhoech** [comment] 2021-02-09 16:00
Confirmed.  The fundamental problem here is that the validation does not allow quantifiers over arrays in node equations.

It should be noted that the node equation could be written much more compactly as `o = (array != pre(array))`.  But, more complex expressions requiring the quantifier form are wanted as well.

**Comment by kfhoech** [comment] 2021-02-09 16:33
Looks like the expressions all expand nicely when used in node and the only change necessary is to allow the NamedID bindings in the validator check over named elements used.

**Comment by kfhoech** [comment] 2021-02-09 16:41
Fixed by 5501aaca0d830135ba6873e2f9dfa45caa910b22.

**Closed by kfhoech** 2021-02-09 16:41 UTC
Labels: AGREE, enhancement
