### ISSUE TITLE
AGREE Array Existential Quantification always returns TRUE

### ISSUE THREAD

**Issue by cong-liu-2000** [loonwerks/AGREE#39] opened 2020-11-23 16:47 UTC
AGREE Definition:
Existential Quantification
A proposition may be stated to hold for some elements in an array
exists bindingName in arrayExpr , boolExpr

Example AGREE code:   
fun IS_DUPLICATE(mission : CMASI::MissionCommand.i, waypoint : CMASI::Waypoint.i) : bool =
            exists wp in mission.WaypointList, not IS_LAST_WAYPOINT(wp) and wp.Number = waypoint.NextWaypoint and wp.Latitude = waypoint.Latitude and wp.Longitude = waypoint.Longitude and wp.Altitude = waypoint.Altitude;

Translated Lustre code:
node CASEAgree__IS_DUPLICATE(
  mission : CMASI__MissionCommand__i;
  waypoint : CMASI__Waypoint__i
) returns (
  _outvar : bool
);
let
  _outvar = true;

tel;

**Comment by kfhoech** [comment] 2020-12-02 15:49
CONFIRMED.

Using the simple model based the suggestion above:

```
package ExistsExpr
public
	with Base_Types;
	
	data Waypoint
	end Waypoint;
	
	data implementation Waypoint.i
		subcomponents
			Number : data Base_Types::Integer;
			NextWaypoint : data Base_Types::Integer;
			Latitude : data Base_Types::Float;
			Longitude : data Base_Types::Float;
			Altitude : data Base_Types::Float;
	end Waypoint.i;

	data MissionCommand
	end MissionCommand;

	data implementation MissionCommand.i
		subcomponents
			WaypointList : data Waypoint.i[10];
	end MissionCommand.i;

	annex agree {**
		fun IS_LAST_WAYPOINT(waypoint : Waypoint.i) : bool =
			waypoint.Number = waypoint.NextWaypoint;
		fun IS_DUPLICATE(mission : MissionCommand.i, waypoint : Waypoint.i) : bool =
			exists wp in mission.WaypointList,
				not IS_LAST_WAYPOINT(wp) and wp.Number = waypoint.NextWaypoint
					and wp.Latitude = waypoint.Latitude and wp.Longitude = waypoint.Longitude
					and wp.Altitude = waypoint.Altitude;
	**};
	
	system WaypointManager
		features
			NoDuplicateWaypoints : out data port Base_Types::Boolean;
		annex agree {**
			eq Mission : MissionCommand.i;
			guarantee "No Duplicate Waypoints" : forall wp in Mission.WaypointList, not IS_DUPLICATE(Mission, wp);
		**};
	end WaypointManager;

end ExistsExpr;
```

**Comment by kfhoech** [comment] 2020-12-02 15:54
Looks like this is a simple copy-paste error in the translation code.  The expansion of the expression should start with false rather than true.

**Comment by kfhoech** [comment] 2020-12-02 16:02
Fixed in code base.

**Closed by kfhoech** 2020-12-02 16:02 UTC
Labels: AGREE, bug
